"""Initial migration

Revision ID: af969812056e
Revises: 
Create Date: 2022-11-28 11:26:23.248742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af969812056e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisites', sa.Text(), nullable=False))
        batch_op.drop_column('prerequisities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisities', sa.TEXT(), nullable=False))
        batch_op.drop_column('prerequisites')

    # ### end Alembic commands ###
